"""Add CA review fields to filing_records

Revision ID: 6b1e2b22d96c
Revises: 6c31f73f7e08
Create Date: 2026-02-12 18:43:33.544055

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '6b1e2b22d96c'
down_revision = '6c31f73f7e08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filing_records', sa.Column('ca_id', sa.Integer(), nullable=True))
    op.add_column('filing_records', sa.Column('ca_notes', sa.Text(), nullable=True))
    op.add_column('filing_records', sa.Column('ca_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('filing_records', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('filing_records', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.create_index(op.f('ix_filing_records_ca_id'), 'filing_records', ['ca_id'], unique=False)
    op.create_foreign_key(None, 'filing_records', 'ca_users', ['ca_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'filing_records', type_='foreignkey')
    op.drop_index(op.f('ix_filing_records_ca_id'), table_name='filing_records')
    op.alter_column('filing_records', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_column('filing_records', 'updated_at')
    op.drop_column('filing_records', 'ca_reviewed_at')
    op.drop_column('filing_records', 'ca_notes')
    op.drop_column('filing_records', 'ca_id')
    # ### end Alembic commands ###