"""Add itr_drafts table

Revision ID: 6c31f73f7e08
Revises: a1b2c3d4e5f6
Create Date: 2026-02-12 17:59:11.895409

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '6c31f73f7e08'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itr_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ca_id', sa.Integer(), nullable=True),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('assessment_year', sa.String(length=10), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('merged_data_json', sa.Text(), nullable=True),
    sa.Column('mismatch_json', sa.Text(), nullable=True),
    sa.Column('checklist_json', sa.Text(), nullable=True),
    sa.Column('ca_notes', sa.Text(), nullable=True),
    sa.Column('ca_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_gst_filing_ids', sa.Text(), nullable=True),
    sa.Column('filing_record_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['ca_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['filing_record_id'], ['filing_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itr_drafts_ca_id'), 'itr_drafts', ['ca_id'], unique=False)
    op.create_index(op.f('ix_itr_drafts_user_id'), 'itr_drafts', ['user_id'], unique=False)
    op.create_index(op.f('ix_business_clients_ca_id'), 'business_clients', ['ca_id'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_business_clients_ca_id'), table_name='business_clients')
    op.drop_index(op.f('ix_itr_drafts_user_id'), table_name='itr_drafts')
    op.drop_index(op.f('ix_itr_drafts_ca_id'), table_name='itr_drafts')
    op.drop_table('itr_drafts')
    # ### end Alembic commands ###