"""make invoice_date nullable

Revision ID: 2a9a70251fe5
Revises: 702898a58ff9
Create Date: 2025-12-09 14:14:23.438400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9a70251fe5'
down_revision: Union[str, Sequence[str], None] = '702898a58ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
