"""add raw_text to invoices

Revision ID: 702898a58ff9
Revises: 
Create Date: 2025-12-09 14:08:38.516167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '702898a58ff9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('supplier_gstin', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('receiver_gstin', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('invoice_number', sa.String(length=50), nullable=False))
    op.add_column('invoices', sa.Column('recipient_gstin', sa.String(length=15), nullable=True))
    op.add_column('invoices', sa.Column('place_of_supply', sa.String(length=2), nullable=True))
    op.add_column('invoices', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('cgst_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('sgst_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('igst_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('supplier_gstin_valid', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('receiver_gstin_valid', sa.Boolean(), nullable=True))
    op.alter_column('invoices', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('invoices', 'taxable_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('invoices_user_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sessions', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('sessions', 'step',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sessions', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('uniq_active_session_per_user'), table_name='sessions', postgresql_where='(active = true)')
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'whatsapp_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'whatsapp_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'])
    op.create_index(op.f('uniq_active_session_per_user'), 'sessions', ['user_id'], unique=True, postgresql_where='(active = true)')
    op.alter_column('sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sessions', 'step',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sessions', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_user_id_fkey'), 'invoices', 'users', ['user_id'], ['id'])
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'taxable_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('invoices', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('invoices', 'receiver_gstin_valid')
    op.drop_column('invoices', 'supplier_gstin_valid')
    op.drop_column('invoices', 'tax_rate')
    op.drop_column('invoices', 'igst_amount')
    op.drop_column('invoices', 'sgst_amount')
    op.drop_column('invoices', 'cgst_amount')
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'place_of_supply')
    op.drop_column('invoices', 'recipient_gstin')
    op.drop_column('invoices', 'invoice_number')
    op.drop_column('invoices', 'receiver_gstin')
    op.drop_column('invoices', 'supplier_gstin')
    # ### end Alembic commands ###
